### ISSUE TITLE
error: 'class TwoWire' has no member named  'setClock'

### ISSUE THREAD

**Issue by jonnymoonshine** [sparkfun/SparkFun_RFD77402_Arduino_Library#4]
Hi. I've been trying to get my new Sparkfun RFD77402 sensors working using this library and the included examples but i'm getting the error "''class TwoWire' has no member named  'setClock'". i'm using the Arduino Create platform so I assume their libraries are up-to-date, and when I look at the Wire.h library on github there is most definitely a member named 'setClock' in the TwoWire class definition! Can anyone out there offer some insight into this?

**Comment by nseidle** [comment]
[Wire.setClock()](https://www.arduino.cc/en/Reference/WireSetClock) is a pretty standard function. I'm not sure if it's the library or Arduino Create. What Arduino are you using the the RFD sensor with?

**Comment by jonnymoonshine** [comment]
Hi Nathan, thanks for your reply! I've sorted out my problem - I was using
Arduino Create to port code to a raspberry Pi, turns out I needed a ported
version of the wire library. I used PiDuino if anyone else has the same
problem.

**Comment by nseidle** [comment]
Good to hear. I had not heard of PiDuino - neat!

Closing issue.
