### ISSUE TITLE
Connecting 2 or more RFD77402 sensors

### ISSUE THREAD

**Issue by yanivfranco** [sparkfun/SparkFun_RFD77402_Arduino_Library#5]
Is there any way or example how to connect more than 1 sensor to arduino?
I'm having trouble with connecting more than 1 because the I2C address is the same ...

Thanks for the help!

**Comment by nseidle** [comment]
The best way is to use an [I2C mux](https://www.sparkfun.com/products/14685). This would allow you to hook up 8 per board, and even chain mux boards together for over 100 RFD77402 is need be.
